const x = null
const o = 9

export const level = [
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [o, o, o, o, o, x, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [o, o, o, o, o, x, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [o, o, o, o, o, o, o, o, o, o, o, o, o, x, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [o, o, o, o, o, x, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [o, o, o, o, o, x, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [o, o, o, o, o, o, o, o, o, o, o, o, o, x, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, x, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o, o],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
  [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x],
]
